apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: airflow
  region: us-east-2
  version: "1.21"
vpc:
  subnets:
    private:
      us-east-2b: { id: subnet-0425cbf9aa121e671 }
      us-east-2c: { id: subnet-07accfda00d1f3be0 }
    public:
      us-east-2b: { id: subnet-0293727f }
      us-east-2c: { id: subnet-2398d16f }
      
managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    privateNetworking: true
    minSize: 1
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: airflow-workstation
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true
